# GitHub repository module configuration
# Generated by Azure GitHub Environment Bootstrap migration script
module "github_repository" {
  source  = "pagopa-dx/github-environment-bootstrap/github"
  version = "~> 1.0"

  repository = {
    name                     = local.repository.name
    description              = local.repository.description
    topics                   = local.repository.topics
    reviewers_teams          = local.repository.reviewers_teams
    default_branch_name      = local.repository.default_branch_name
    jira_boards_ids          = local.repository.jira_boards_ids
    infra_cd_policy_branches = local.repository.infra_cd_policy_branches
    opex_cd_policy_branches  = local.repository.opex_cd_policy_branches
    app_cd_policy_branches   = local.repository.app_cd_policy_branches
    environments             = ["prod", "psn-prod"]
  }
}

resource "github_actions_secret" "slack_webhook_url" {
  repository      = local.repository.name
  secret_name     = "SLACK_WEBHOOK_URL"
  plaintext_value = "PLACEHOLDER"

  lifecycle {
    ignore_changes = [remote_updated_at]
  }
}

resource "github_repository_environment" "automation_prod_cd" {
  environment = "automation-prod-cd"
  repository  = module.github_repository.name

  deployment_branch_policy {
    protected_branches     = true
    custom_branch_policies = false
  }
}
