# Repository module outputs
# Generated by Azure GitHub Environment Bootstrap migration script
output "repository_id" {
  description = "The ID of the GitHub repository"
  value       = module.github_repository.id
}

output "repository_name" {
  description = "The name of the GitHub repository"
  value       = module.github_repository.name
}
