openapi: 3.0.3
info:
  title: IO Wallet
  version: 1.0.0
paths:
  /.well-known/openid-federation:
    get:
      operationId: getEntityConfiguration
      summary: Returns entity configuration
      responses:
        "200":
          description: Successful operation
          content:
            application/entity-statement+jwt:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        "500":
          $ref: "#/components/responses/Unexpected"

  /nonce:
    get:
      operationId: getNonce
      summary: Returns a randomly generated nonce
      responses:
        "200":
          description: Nonce successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  nonce:
                    type: string
        "500":
          $ref: "#/components/responses/Unexpected"

  /users:
    post:
      operationId: getUserIdByFiscalCode
      summary: Returns the user id given the fiscal code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fiscal_code:
                  $ref: "#/components/schemas/FiscalCode"
              required:
                - fiscal_code
      responses:
        "200":
          description: User id successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/Id"
                required:
                  - id
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/Unexpected"

  /wallet-instance:
    post:
      operationId: createWalletInstance
      summary: Create a wallet instance
      parameters:
        - in: header
          name: x-iowallet-fiscal-code
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                challenge:
                  type: string
                  format: binary
                key_attestation:
                  type: string
                  format: binary
                hardware_key_tag:
                  type: string
      responses:
        "204":
          description: Wallet instance successfully created
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/Unexpected"

  /health:
    get:
      operationId: healthCheck
      summary: Used to check if the function is active
      responses:
        "200":
          description: The function is health
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          $ref: "#/components/responses/Unexpected"

components:
  responses:
    UnprocessableContent:
      description: Unprocessable Content
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"

    Unexpected:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"

  schemas:
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: >-
            A short, summary of the problem type. Written in english and
            readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: >-
            The HTTP status code generated by the origin server for this
            occurrence of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 200
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: >-
            An absolute URI that identifies the specific occurrence of the
            problem. It may or may not yield further information if
            dereferenced.

    FiscalCode:
      type: string
      description: User's fiscal code.
      format: FiscalCode
      x-import: "@pagopa/ts-commons/lib/strings"
      example: SPNDNL80R13C555X

    Id:
      type: string
      description: UUID
      example: 32928ece-6ca0-488c-9a6a-eb8ee66ab69a
