packages:
  - apps/*
  - packages/*

catalog:
  '@azure/cosmos': ^4.9.1
  '@azure/functions': ^4.11.2
  '@azure/identity': ^4.13.0
  '@azure/storage-blob': ^12.31.0
  '@azure/storage-queue': ^12.29.0
  '@pagopa/handler-kit': ^1.1.1
  '@pagopa/handler-kit-azure-func': ^2.0.8
  '@pagopa/logger': ^1.0.1
  '@pagopa/ts-commons': ^13.1.2
  fp-ts: ^2.16.11
  io-ts: ^2.2.22

linkWorkspacePackages: true
packageImportMethod: "clone-or-copy"
cleanupUnusedCatalogs: true
injectWorkspacePackages: true

onlyBuiltDependencies:
  - azure-functions-core-tools
  - cbor-extract
  - esbuild
  - protobufjs

packageExtensions:
  '@azure/functions-opentelemetry-instrumentation':
    dependencies:
      '@opentelemetry/api-logs': 0.52.1
