oa3_spec: apps/io-wallet-user-func/openapi.yaml
name: opex_io_wallet
location: Italy North
timespan: 5m
evaluation_frequency: 10
evaluation_time_window: 30
event_occurrences: 4 # After 5*4=20 min
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-external/providers/Microsoft.Network/applicationGateways/io-p-appgateway
action_groups:
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-itn-wallet-rg-01/providers/Microsoft.Insights/actiongroups/io-p-itn-wallet-ag-01
overrides:
  hosts:
    - api-app.io.pagopa.it
  endpoints:
    /api/v1/wallet/wallet-instances/{id}/status:
      response_time_threshold: 10
