oa3_spec: apps/io-wallet-user-func/openapi.yaml
name: opex_io_wallet
location: Italy North
timespan: 5m
evaluation_frequency: 10
evaluation_time_window: 30
event_occurrences: 4 # After 5*4=20 min
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-itn-common-rg-01/providers/Microsoft.Network/applicationGateways/io-p-itn-agw-01
# action_groups:
#   - /subscriptions/<REPLACE_WITH_PSN_SUBSCRIPTION_ID>/resourceGroups/<REPLACE_WITH_PSN_WALLET_RESOURCE_GROUP>/providers/Microsoft.Insights/actionGroups/iw-p-itn-ag-01
overrides:
  hosts:
    - api-app.io.pagopa.it
  endpoints:
    /api/wallet/v1/wallet-instances/{id}/status:
      availability_threshold: 0.99
      availability_evaluation_frequency: 10
      availability_evaluation_time_window: 20
      availability_event_occurrences: 1
      response_time_threshold: 5
      response_time_evaluation_frequency: 10
      response_time_evaluation_time_window: 20
      response_time_event_occurrences: 1
