openapi: 3.0.1
info:
  title: IT-Wallet User - PDND UAT v1
  description: REST APIs consumed by PDND in UAT
  version: v1
paths:
  "/wallet-instances/status":
    put:
      summary: SetWalletInstancesStatus
      operationId: setWalletInstancesStatus
      description: Revoke all valid Wallet Instances associated with the specified fiscal code.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetWalletInstancesStatusData"
      responses:
        "204":
          description: Wallet Instances status successfully set
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
components:
  responses:
    UnprocessableContent:
      description: Unprocessable Content
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
  schemas:
    SetWalletInstancesStatusData:
      type: object
      properties:
        status:
          type: string
          enum:
            - REVOKED
        fiscal_code:
          $ref: "#/components/schemas/FiscalCode"
        reason:
          type: string
          enum:
            - USER_DECEASED
      required:
        - status
        - fiscal_code
        - reason
    FiscalCode:
      type: string
      description: User's fiscal code.
      format: FiscalCode
      x-import: "@pagopa/ts-commons/lib/strings"
      example: SPNDNL80R13C555X
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: "A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable"
        status:
          type: integer
          format: int32
          description:
            The HTTP status code generated by the origin server for this
            occurrence of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description:
            An absolute URI that identifies the specific occurrence of
            the problem. It may or may not yield further information if dereferenced.
