# This workflow will perform the code review on each code change.
# It uses "actions/cache" and turborepo in order to perform tasks only on changed files.

name: "Code Review"

on:
  push:
    branches: ["main", "master"]
    paths:
      - apps/**
      - packages/**
  pull_request:
    types: [opened, synchronize]
    paths:
      - apps/**
      - packages/**
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 #v3.3.1
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: "Build"
        run: yarn run build

      - name: "Code review"
        run: yarn run code-review

  list_standalone_packages: # list all stand alone packages
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-packages.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: list-packages
        run: |
          ls -d packages-sa/*
          echo "::set-output name=matrix::$(ls -d packages-sa/* | jq -R -s -c 'split("\n")[:-1]')" # all subdir of packages-sa

  code_review_standalone: # core review each stand alone package
    needs: list_standalone_packages
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package_dir: ${{ fromJson(needs.list_standalone_packages.outputs.matrix) }}
    steps:
      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          cache: "yarn"

      - name: Navigate to package folder
        run: |
          echo "Navigate to ${{ matrix.package_dir }}"
          cd ${{ matrix.package_dir }}

      - name: Install dependencies
        run: yarn

      - name: "Code review"
        run: yarn run code-review
