# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request and its title.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: "Labeler"

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      pull-requests: write

    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        name: Checkout

      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

      # Note that the following step
      # never removes labels
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: set-result
        with:
          script: |
            const config = {
              docs: /^docs/,
              bug: /^bug/,
              fix: /^fix/,
              chore: /^chore/,
              feat: /^feat/,
              build: /^build/,
              ci: /^ci/,
              refactor: /^refactor/,
              "breaking-change": /!:/,
            };

            const labels = Object.entries(config).reduce(
              (acc, cur) => (context.payload.pull_request.title.match(cur[1])
                ? [...acc, cur[0]] : acc),
              []
            );

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
            }
          result-encoding: string
