name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "infra/resources/prod/**"
      - "infra/resources/_modules/**"

jobs:
  release_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
