name: Deploy Function App (support-func)

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "apps/io-wallet-support-func/CHANGELOG.md"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/release-azure-appsvc-v1.yaml@b1d89c1794de24a07f6c3faf7ce2eed448921815
    secrets: inherit
    with:
      workspace_name: io-wallet-support-func
      environment: app-prod
      resource_group_name: io-p-itn-wallet-rg-01
      web_app_name: io-p-itn-wallet-supp-func-01
      disable_auto_staging_deploy: true
