name: Deploy Function App (user-func)

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@f09aec9635f1b6f550dd90d2d2581d3e5239b409
    secrets: inherit
    with:
      workspace_name: io-wallet-user-func
      environment: app-prod
      resource_group_name: io-p-itn-wallet-rg-01
      function_app_name: io-p-itn-wallet-user-func-01
      health_check_path: "/health"