name: Deploy Function App (user-func)

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "apps/io-wallet-user-func/**"

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
    secrets: inherit
    with:
      workspace_name: io-wallet-user-func
      environment: app-prod
      resource_group_name: io-p-itn-wallet-rg-01
      function_app_name: io-p-itn-wallet-user-func-01
      health_check_path: "/health"
      use_staging_slot: false
      use_private_agent: false
